name: Print Text File
    
on: 
  push:
    branches:
      - master

jobs: 
   read_the_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read and print the text file
        run: |
          ls -l
          cat hello.txt
          

    